# -*- coding: utf-8 -*-
"""Hospitalizations (multi-states)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu5vgD26ytmiSdMuSmDW8yjaOSgcUw9L
"""

from google.colab import files
uploaded = files.upload()

import os
print("this too check correct path", os.listdir())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# Load hospitalizations CSV
df = pd.read_csv("REGION 9 Invent Health Project - NEITHER REGION ( HOSPITALIZATIONS).csv")

# Convert date column
df["_WeekendDate"] = pd.to_datetime(df["_WeekendDate"])

# Just kept rows with age category info
age_df = df[df["AgeCategory_Legend"].notna()].copy()

# Organize age categories
age_order = [
    '0-4 years',
    '5-11 years',
    '12-17 years',
    '18-29 years',
    '30-39 years',
    '40-49 years',
    '50-64 years',
    '65-74 years',
    '75-84 years',
    '≥85 years'
]

# Set categorical order
age_df["AgeCategory_Legend"] = pd.Categorical(
    age_df["AgeCategory_Legend"], categories=age_order, ordered=True
)

# Set style and figure
sns.set_theme(style="whitegrid")
plt.figure(figsize=(16, 8))

# Plot the lines
sns.lineplot(
    data=age_df,
    x="_WeekendDate",
    y="CumulativeRate",
    hue="AgeCategory_Legend",
    errorbar=None
)

# Clean labels and format
plt.title("Cumulative COVID-19 Hospitalizations by Age Group")
plt.xlabel("Date")
plt.ylabel("Cumulative Hospitalization Rate (per 100k)")
plt.xticks(rotation=0, ha='center')  # fully horizontal dates

# Format x-axis as MM/YYYY
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%m/%Y"))

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# Load hospitalizations CSV
df = pd.read_csv("REGION 9 Invent Health Project - NEITHER REGION ( HOSPITALIZATIONS).csv")

# Convert date column
df["_WeekendDate"] = pd.to_datetime(df["_WeekendDate"])

# Just keep rows with valid state info and the right rate type
state_df = df[(df["State"].notna()) & (df["Type"] == "Crude Rate")].copy()

# Set style and figure
sns.set_theme(style="whitegrid")
plt.figure(figsize=(16, 8))

# Plot cumulative rate over time, one line per state, no shaded area
sns.lineplot(
    data=state_df,
    x="_WeekendDate",
    y="CumulativeRate",
    hue="State",
    ci=None   # 🔻 removes shaded confidence intervals
)

# Clean labels and formatting
plt.title("Cumulative COVID-19 Hospitalizations by State")
plt.xlabel("Date")
plt.ylabel("Cumulative Hospitalization Rate (per 100k)")
plt.xticks(rotation=0, ha='center')  # horizontal dates

# Format x-axis as MM/YYYY
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%m/%Y"))

plt.tight_layout()
plt.show()