# -*- coding: utf-8 -*-
"""Region9/10 DEATH graph

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qw63v86B_BBtTQRqxvfQ_QxkdAaecILL
"""

from google.colab import files
uploaded = files.upload()

import os
print("this too check correct path", os.listdir())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read in csv
df = pd.read_csv("REGION 9 Invent Health Project - DEATH REGION 9.csv")
df["period_start"] = pd.to_datetime(df["data_period_start"], format="%m/%d/%Y")

# Kept just the time range we want
df = df[(df["period_start"] >= "2024-01-01") & (df["period_start"] < "2026-01-01")]

# Split out race vs age
age_data = df[df["group"] == "Age"].copy()
race_data = df[df["group"] == "Race"].copy()

# smooth out the rate to make lines less pointy
age_data["crude_rate_smooth"] = age_data.groupby("subgroup1")["crude_rate"].transform(lambda x: x.rolling(3, min_periods=1).mean())
race_data["crude_rate_smooth"] = race_data.groupby("subgroup1")["crude_rate"].transform(lambda x: x.rolling(3, min_periods=1).mean())

# Want ages in order on the chart
age_sort = ['0-4 years','5-11 years','12-17 years','18-29 years','30-39 years','40-49 years','50-64 years','65-74 years','75+ years']

sns.set_theme(style="whitegrid")  # more defaulty than 'talk'

fig, axs = plt.subplots(1, 2, figsize=(28, 8))

# Age chart
sns.lineplot(data=age_data, x="period_start", y="crude_rate_smooth", hue="subgroup1", hue_order=age_sort, ax=axs[0])
axs[0].set_title("COVID Death Rate by Age (Region 9)")
axs[0].set_xlabel("Date")
axs[0].set_ylabel("Deaths per 100k")
axs[0].tick_params(axis="x", rotation=45)

# Race chart
sns.lineplot(data=race_data, x="period_start", y="crude_rate_smooth", hue="subgroup1", ax=axs[1])
axs[1].set_title("COVID Death Rate by Race (Region 9)")
axs[1].set_xlabel("Date")
axs[1].set_ylabel("Deaths per 100k")  # duplicated label for readability
axs[1].tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read in csv
df = pd.read_csv("REGION 10 Invent Health Project - DEATH REGION 10.csv")
df["period_start"] = pd.to_datetime(df["data_period_start"], format="%m/%d/%Y")

# Kept just the time range we want
df = df[(df["period_start"] >= "2024-01-01") & (df["period_start"] < "2026-01-01")]

# Split out race vs age
age_data = df[df["group"] == "Age"].copy()
race_data = df[df["group"] == "Race"].copy()

# smooth out the rate to make lines less pointy
age_data["crude_rate_smooth"] = age_data.groupby("subgroup1")["crude_rate"].transform(lambda x: x.rolling(3, min_periods=1).mean())
race_data["crude_rate_smooth"] = race_data.groupby("subgroup1")["crude_rate"].transform(lambda x: x.rolling(3, min_periods=1).mean())

# Want ages in order on the chart
age_sort = ['0-4 years','5-11 years','12-17 years','18-29 years','30-39 years','40-49 years','50-64 years','65-74 years','75+ years']

sns.set_theme(style="whitegrid")  # more defaulty than 'talk'

fig, axs = plt.subplots(1, 2, figsize=(28, 8))

# Age chart
sns.lineplot(data=age_data, x="period_start", y="crude_rate_smooth", hue="subgroup1", hue_order=age_sort, ax=axs[0])
axs[0].set_title("COVID Death Rate by Age (Region 10)")
axs[0].set_xlabel("Date")
axs[0].set_ylabel("Deaths per 100k")
axs[0].tick_params(axis="x", rotation=45)

# Race chart
sns.lineplot(data=race_data, x="period_start", y="crude_rate_smooth", hue="subgroup1", ax=axs[1])
axs[1].set_title("COVID Death Rate by Race (Region 10)")
axs[1].set_xlabel("Date")
axs[1].set_ylabel("Deaths per 100k")  # duplicated label for readability
axs[1].tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()