# -*- coding: utf-8 -*-
"""Unemployment graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjgPZsx66zazsDF1_vkisqYw8qtmJODQ
"""

from google.colab import files
uploaded = files.upload()

import os
print("this too check correct path", os.listdir())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# Load the dataset
unemp_df = pd.read_csv("Unemployment Data - Unemployment Data.csv")

# turn all month‑columns into rows
unemp_long = unemp_df.melt(
    id_vars="State",
    var_name="Month",
    value_name="Unemployment Rate"
)

#  Change month strings to real dates
unemp_long["Date"] = pd.to_datetime(unemp_long["Month"], format="%b %Y")

# Filter to Jan 2019 onward
filtered = unemp_long[unemp_long["Date"] >= "2019-01-01"].copy()

# Define your two regions
region_9_states  = ["Arizona", "California", "Hawaii", "Nevada"]
region_10_states = ["Alaska", "Idaho", "Oregon", "Washington"]

# Helper: list of years to annotate (start and mid)
start_year = filtered["Date"].dt.year.min()
end_year   = filtered["Date"].dt.year.max()
years = range(start_year, end_year + 1)

# Region 9
r9 = filtered[filtered["State"].isin(region_9_states)]

sns.set_theme(style="whitegrid")
plt.figure(figsize=(16, 8))

sns.lineplot(
    data=r9,
    x="Date",
    y="Unemployment Rate",
    hue="State",
    errorbar=None
)

# Add vertical lines at start (Jan 1) and mid (Jul 1) of each year
for y in years:
    plt.axvline(pd.Timestamp(f"{y}-01-01"), color="grey", linestyle="--", linewidth=0.8)
    plt.axvline(pd.Timestamp(f"{y}-07-01"), color="grey", linestyle="--", linewidth=0.8)

# Clean labels and format Region 9 plot
plt.title("Region 9 Unemployment Rate by State (Jan 2019–Present)")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%m/%Y"))
plt.xticks(rotation=0, ha="center")
plt.tight_layout()
plt.show()

# Region 10
r10 = filtered[filtered["State"].isin(region_10_states)]

sns.set_theme(style="whitegrid")
plt.figure(figsize=(16, 8))

sns.lineplot(
    data=r10,
    x="Date",
    y="Unemployment Rate",
    hue="State",
    errorbar=None
)

# Add vertical lines at start (Jan 1) and mid (Jul 1) of each year
for y in years:
    plt.axvline(pd.Timestamp(f"{y}-01-01"), color="grey", linestyle="--", linewidth=0.8)
    plt.axvline(pd.Timestamp(f"{y}-07-01"), color="grey", linestyle="--", linewidth=0.8)

# Clean labels and format Region 10 plot
plt.title("Region 10 Unemployment Rate by State (Jan 2019–Present)")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%m/%Y"))
plt.xticks(rotation=0, ha="center")
plt.tight_layout()
plt.show()